### ISSUE TITLE
issue with association?

### ISSUE THREAD

**Issue by chiperific** [GBH/delayed_job_progress#8]
I'm having trouble with setup.

Calling `user.jobs` gives me this (both before and after creating a job)
`NameError: uninitialized constant User::Delayed::Job`

But, calling `Delayed::Jobs.first.record` performs as expected

I'm running Rails 5.1.6

User.rb:

    class User < ApplicationRecord
      has_many :jobs, as: :record, class_name: 'Delayed::Job'
    end

Migration file is as-generated.

I am using a custom job:

    class SyncUserWithApiJob < ApplicationJob
      def initialize(user_id)
        @user = User.find(user_id)
      end
     
      def enqueue(job)
        job.record       = @user
        job.identifier   = 'user_' + @user.id.to_s + '_api_sync_' + Time.now.utc.rfc3339(3)
        job.progress_max = Property.visible_to(@user).count + Task.visible_to(@user).count
      end
     
      def before(job)
        @job = job
      end

      def perform
        # doing stuff
      end
    end

Any ideas?

**Comment by GBH** [comment]
It's almost like your autoloading doesn't do what it supposed to. Try `has_many :jobs, as: :record, class_name: '::Delayed::Job'`. It's just odd that `Delayed::Job` works directly, but not when you specify it as a `class_name`.

**Comment by chiperific** [comment]
Whoa, that worked!

    2.4.4 :001 > User.first.jobs
      User Load (1.0ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
      Delayed::Backend::ActiveRecord::Job Load (0.9ms)  SELECT  "delayed_jobs".* FROM "delayed_jobs" WHERE "delayed_jobs"."record_id" = $1 AND "delayed_jobs"."record_type" = $2 LIMIT $3  [["record_id", 3], ["record_type", "User"], ["LIMIT", 11]]
     => #<ActiveRecord::Associations::CollectionProxy []> 
    2.4.4 :002 >
