### ISSUE TITLE
job.destroy(:force) in custom job shuts down Foreman?

### ISSUE THREAD

**Issue by chiperific** [GBH/delayed_job_progress#9]
Using Foreman, I wanted to add a `success(job)` method to my custom job.
I also got cocky and thought I would use this to destroy the job since I'm done with it.

However, the following code sends a SIGTERM to Foreman that shuts down both the web and worker process.

    class SyncUserWithApiJob < ApplicationJob
      def initialize(user_id)
        @user = User.find(user_id)
      end

      def enqueue(job)
        job.record            = @user
        job.identifier        = 'user_' + @user.id.to_s + '_api_sync_' + Time.now.utc.rfc3339(3)
        job.progress_max      = Property.visible_to(@user).count + Task.visible_to(@user).count
        job.message           = 'Fetching your tasklists...'
      end

      def before(job)
        @job = job
      end

      def perform
        # all the stuff
      end

      def success(job)
        job.update(message: 'Done!', completed_at: Time.now)
        sleep 4 # just long enough for ajax to catch the message
        job.destroy(:force) # causes Foreman to exit gracefully...
      end
    end

Any ideas why destroying a job would do this?

**Comment by GBH** [comment]
No clue. Maybe something to do with the `sleep` call. 

I kinda did `job.destroy(:force)` to be used as part of a cron job that cleans up completed jobs.

**Comment by chiperific** [comment]
OK, thanks. 
It's not the `sleep` because removing it doesn't solve the problem, but removing the `job.destroy(:force)` line does.

Could be a Foreman issue, could be Delayed::Job... too many code-heavy avenues to chase, so I'll abandon it for now.
